### ISSUE TITLE
Errors on "Play"

### ISSUE THREAD

**Issue by olgv** [keijiro/ThreeDScans#1]
Though it looks good in Scene view, I'm getting this all the time with when hitting play, with a very dark outcome in the Game view.

```
Invalid pass number (8) for Graphics.Blit (Material "Hidden/Kino/Bloom" with 1 passes)
UnityEngine.Graphics:Blit(Texture, RenderTexture, Material, Int32)
Kino.Bloom:OnRenderImage(RenderTexture, RenderTexture) (at Assets/ThreeDScans-master/Kino/Bloom/Bloom.cs:238)
```

The "Invalid pass" number varies between `(1)`, `(3)`, `(4)`, `(6)` and `(8)`

Thanks

**Comment by keijiro** [comment]
Which version of Unity are you using? It might require 5.4.0 or later.

**Comment by olgv** [comment]
Works great in 5.4. 
Might have also been the fact that I was adding the package into an existing 5.3.X debug project.

Great stuff !

**Comment by keijiro** [comment]
Thanks for clarifying :)
