### ISSUE TITLE
Curvature map

### ISSUE THREAD

**Issue by AndreGroeschel** [keijiro/ThreeDScans#2]
Hi Keijiro,

I saw that in some of the models scans there is an additional curvature map. Can you tell me what is it used for and maybe point me to some shader that makes use of it?

Cheers,
André

**Comment by keijiro** [comment]
GreyscaleGorilla's tutorial might be a good starter.

https://greyscalegorilla.com/tutorials/three-ways-to-use-the-arnold-curvature-map/

I used it in DanishStatues example (not a good use though).

https://github.com/keijiro/DanishStatues/blob/master/Assets/Test/DanishStatue.shader

**Comment by AndreGroeschel** [comment]
Cool! Thank you very much!
